// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord 
{ 
static buildTime(): Date { return new Date(2025, (parseInt("08") - 1), parseInt("28"), parseInt("17"), parseInt("57"), parseInt("39")); } 
static version(): string { return "unknown"; } 
} 
