// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord 
{ 
static buildTime(): Date { return new Date(2023, (parseInt("12") - 1), parseInt("07"), parseInt("22"), parseInt("32"), parseInt("07")); } 
static version(): string { return "unknown"; } 
} 
