"use strict";
// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord {
    static buildTime() { return new Date(2024, (parseInt("01") - 1), parseInt("06"), parseInt("17"), parseInt("28"), parseInt("44")); }
    static version() { return "unknown"; }
}
