"use strict";
// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord {
    static buildTime() { return new Date(2023, (11 - 1), 21, 17, parseInt("34"), parseInt("50")); }
    static version() { return "unknown"; }
}
