// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord 
{ 
static buildTime(): Date { return new Date(2023, (parseInt("12") - 1), parseInt("03"), parseInt("15"), parseInt("36"), parseInt("28")); } 
static version(): string { return "unknown"; } 
} 
