"use strict";
// Generated by the _Build.bat or .sh scripts.
class _BuildRecord {
    static buildTime() { return new Date(2024, (parseInt("01") - 1), parseInt("01"), parseInt("06"), parseInt("22"), parseInt("40")); }
    static version() { return "unknown"; }
}
